[profile.default]
src = "src"
out = "out"
libs = ["lib"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

# Monad Testnet Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

# Compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Contract size limits (Monad allows larger contracts)
bytecode_hash = "none"
cbor_metadata = false
